### ISSUE TITLE
newsbeuter crashes when an ISO-8859-1 item title with umlauts is displayed on an UTF-8 terminal

### ISSUE THREAD

**Issue by Minoru** [Minoru/issues-migration-test#10]
_From [theunixe...@gmail.com](https://code.google.com/u/110181941365479991907/) on March 05, 2007 00:46:51_

What steps will reproduce the problem? 1. set your charset to ISO-8859-1
2. reload a feed that contains an umlaut in an item title
3. set your charset to UTF-8
4. open that feed
5. newsbeuter crashes

Here's the backtrace:
\#0  0x080826d6 in newtxt (o=0xbfffe484, fmt=0x808bbc6 "&#37;c&#37;.*s&#37;c") at dump.c:46
\#1  0x08082778 in myquote (txt=0xbfffe484, text=0x87492cc "  68   Mar 02  
Zitat `#78262` - \<MeX> Da steht im neuen Plus-Prospekt doch tatsäc...") at
dump.c:60
\#2  0x080829f3 in stfl_quote_backend (text=0x87492cc "  68   Mar 02   Zitat
\#78262 - \<MeX> Da steht im neuen Plus-Prospekt doch tatsäc...") at dump.c:125
\#3  0x0807fe05 in stfl_quote (text=0x87492cc "  68   Mar 02   Zitat `#78262`
- \<MeX> Da steht im neuen Plus-Prospekt doch tatsäc...") at public.c:125
\#4  0x0804c7bd in newsbeuter::stfl::quote (text=@0xbfffeae0) at
src/stflpp.cpp:78
\#5  0x0806ffc1 in newsbeuter::view::run_itemlist (this=0xbffff338, pos=62,
auto_open=false) at src/view.cpp:410
\#6  0x080757c3 in newsbeuter::controller::open_feed (this=0xbffff2c4,
pos=62, auto_open=false) at src/controller.cpp:285
\#7  0x080715ac in newsbeuter::view::run_feedlist (this=0xbffff338,
tags=@0xbffff224) at src/view.cpp:130
\#8  0x08078a59 in newsbeuter::controller::run (this=0xbffff2c4, argc=5,
argv=0xbffff404) at src/controller.cpp:229
\#9  0x0804bf13 in main (argc=5, argv=0xbffff404) at newsbeuter.cpp:24

This is an architectural problem. Currently, the title and the description
are converted when the download happens. When the charset changes between
reload and displaying, we have a problem, because the charset of the title
doesn't match the current charset anymore, and then (v)asprintf (which is
used by STFL) fails, which ultimately leads to the crash above.

This should be changed that it is converted whenever it is displayed.

_Original issue: http://code.google.com/p/newsbeuter/issues/detail?id=10_

**Comment by Minoru** [comment]
_From [theunixe...@gmail.com](https://code.google.com/u/110181941365479991907/) on March 05, 2007 04:36:06_

Fixed in the SVN.

**Status:** Fixed
